# Generated by Django 2.2 on 2020-05-27 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models
import uuid
import videokit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Open', 'Open'), ('Delivered', 'Delivered'), ('Production', 'Production')], max_length=255)),
                ('editor', models.ForeignKey(blank=True, limit_choices_to={'editor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_editor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='VideoSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('video', videokit.models.VideoField(blank=True, duration_field='video_duration', height_field='video_height', mimetype_field='video_mimetype', null=True, rotation_field='video_rotation', thumbnail_field='video_thumbnail', upload_to=events.models.user_directory_path, width_field='video_width')),
                ('video_width', models.IntegerField(blank=True, null=True)),
                ('video_height', models.IntegerField(blank=True, null=True)),
                ('video_rotation', models.FloatField(blank=True, null=True)),
                ('video_mimetype', models.CharField(blank=True, max_length=32, null=True)),
                ('video_duration', models.IntegerField(blank=True, null=True)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_mp4', videokit.models.VideoSpecField(blank=True, null=True, upload_to='')),
                ('video_ogg', videokit.models.VideoSpecField(blank=True, null=True, upload_to='')),
                ('video_webm', videokit.models.VideoSpecField(blank=True, null=True, upload_to='')),
                ('uploaded_by', models.CharField(max_length=255, verbose_name='From:')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('production_order', models.PositiveIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
