# Generated by Django 2.2 on 2020-05-28 22:23

from django.db import migrations, models
import events.models
import videokit.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosubmission',
            options={'ordering': ['production_order', 'timestamp']},
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Production', 'Production'), ('Delivered', 'Delivered'), ('Open', 'Open')], max_length=255),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='video',
            field=videokit.models.VideoField(duration_field='video_duration', height_field='video_height', mimetype_field='video_mimetype', rotation_field='video_rotation', thumbnail_field='video_thumbnail', upload_to=events.models.user_directory_path, width_field='video_width'),
        ),
    ]
