# Generated by Django 2.2 on 2020-05-29 14:19

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200528_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.user_event_directory_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Delivered', 'Delivered'), ('Open', 'Open'), ('Production', 'Production')], max_length=255),
        ),
    ]
