# Generated by Django 2.2.10 on 2020-05-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200529_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Production', 'Production'), ('Open', 'Open'), ('Complete', 'Complete')], max_length=255),
        ),
    ]
