# Generated by Django 2.2.10 on 2020-05-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200531_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Production', 'Production'), ('Complete', 'Complete'), ('Delivered', 'Delivered'), ('Open', 'Open')], max_length=255),
        ),
    ]
