# Generated by Django 2.2.10 on 2020-05-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200531_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Open', 'Open for Submissions'), ('Production', 'Being Produced'), ('Delivered', 'Final Product'), ('Complete', 'Complete')], max_length=255),
        ),
    ]
