# Generated by Django 2.2.10 on 2020-06-05 13:44

from django.db import migrations, models
import events.models
import videokit.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='final_video',
            field=videokit.models.VideoField(blank=True, null=True, thumbnail_field='final_video_thumbnail', upload_to=events.models.user_event_directory_path),
        ),
        migrations.AddField(
            model_name='event',
            name='final_video_mp4',
            field=videokit.models.VideoSpecField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='final_video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='videosubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
