# Generated by Django 2.2.10 on 2020-06-08 23:33

from django.db import migrations
import events.models
import videokit.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200605_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosubmission',
            name='video_duration',
        ),
        migrations.RemoveField(
            model_name='videosubmission',
            name='video_height',
        ),
        migrations.RemoveField(
            model_name='videosubmission',
            name='video_mimetype',
        ),
        migrations.RemoveField(
            model_name='videosubmission',
            name='video_rotation',
        ),
        migrations.RemoveField(
            model_name='videosubmission',
            name='video_width',
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='video',
            field=videokit.models.VideoField(thumbnail_field='video_thumbnail', upload_to=events.models.user_directory_path),
        ),
    ]
