# Generated by Django 2.2.10 on 2021-02-09 00:45

import django.core.files.storage
from django.db import migrations, models
import events.models
import videokit.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200609_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.user_event_image_directory_path),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='video',
            field=videokit.models.VideoField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/jaredtangir/Desktop/TESTING'), thumbnail_field='video_thumbnail', upload_to=events.models.user_directory_path),
        ),
    ]
