# Generated by Django 2.2.10 on 2021-02-13 00:40

import django.core.files.storage
from django.db import migrations
import events.models
import videokit.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210209_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='final_video',
            field=videokit.models.VideoField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/jaredtangir/Desktop/TESTING'), thumbnail_field='final_video_thumbnail', upload_to=events.models.user_event_directory_path),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='video',
            field=videokit.models.VideoField(storage=django.core.files.storage.FileSystemStorage(location='/Users/jaredtangir/Desktop/TESTING'), thumbnail_field='video_thumbnail', upload_to=events.models.user_directory_path),
        ),
    ]
