# Generated by Django 2.2.10 on 2020-06-04 18:10

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200531_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='US/Eastern'),
        ),
    ]
