# Generated by Django 2.2.10 on 2020-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_eventcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='addtl_video_price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Price per Additional Video'),
        ),
        migrations.AddField(
            model_name='package',
            name='included_videos',
            field=models.PositiveIntegerField(default=10, verbose_name='Included Videos'),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_videos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='min_videos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
