# Generated by Django 2.2.10 on 2020-06-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200615_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoupon',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Package'),
        ),
    ]
